services:
  sonarr:
    build: .
    image: local/sonarr-fallback:dev
    container_name: sonarr-test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - C:/docker/sonarr-test/config:/config
      - G:/Torrent:/downloads
      - G:/Plex/Series:/tv
    ports:
      - 8989:8989
    restart: unless-stopped
