// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fallbackButton': string;
  'filterMenuContainer': string;
  'filteredMessage': string;
}
export const cssExports: CssExports;
export default cssExports;
